version: "3"
services:
  postgres:
    image: "postgres:15" 
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/initdb:/${POSTGRES_DB}/initdb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - zuninetwork

  adminer:
    image: adminer
    links:
      - postgres:postgres
    ports:
      - 8080:8080
    networks:
      - zuninetwork

volumes:
  pg_data:

networks:
  zuninetwork: