DROP TABLE IF EXISTS "Workers" CASCADE;
DROP TABLE IF EXISTS "WorkerStatus" CASCADE;
DROP TABLE IF EXISTS "Vehicles" CASCADE;
DROP TABLE IF EXISTS "VehicleStatus" CASCADE;
DROP TABLE IF EXISTS "MCPs" CASCADE;
DROP TABLE IF EXISTS "MCPStatus" CASCADE;
DROP TABLE IF EXISTS "Routes" CASCADE;
DROP TABLE IF EXISTS "Workers" CASCADE;
DROP TABLE IF EXISTS "BackOfficers" CASCADE;
DROP TABLE IF EXISTS "Tasks" CASCADE;

DROP TYPE IF EXISTS "WorkerType";
DROP TYPE IF EXISTS "GenderType";
DROP TYPE IF EXISTS "WorkerStatusType";
DROP TYPE IF EXISTS "VehicleStatusType";
DROP TYPE IF EXISTS "TaskStatusType";