// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"
)

type Querier interface {
	CreateBackOfficers(ctx context.Context, arg CreateBackOfficersParams) (BackOfficer, error)
	GetBackOfficer(ctx context.Context, email string) (BackOfficer, error)
}

var _ Querier = (*Queries)(nil)
