// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: routes.sql

package db

import (
	"context"
)

const createRoute = `-- name: CreateRoute :one
INSERT INTO
  "Routes" (
    "start_location",
    "end_location",
    "distance",
    "estimated_time"
  )
VALUES
  ($1, $2, $3, $4)
RETURNING id, start_location, end_location, distance, estimated_time, created_at, updated_at
`

type CreateRouteParams struct {
	StartLocation string `json:"start_location"`
	EndLocation   string `json:"end_location"`
	Distance      string `json:"distance"`
	EstimatedTime string `json:"estimated_time"`
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRowContext(ctx, createRoute,
		arg.StartLocation,
		arg.EndLocation,
		arg.Distance,
		arg.EstimatedTime,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.StartLocation,
		&i.EndLocation,
		&i.Distance,
		&i.EstimatedTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
